- name: restart nomad
  service:
    name: nomad
    state: restarted

- name: reload consul
  service:
    name: consul
    state: reloaded

- name: reload systemd
  command: systemctl daemon-reload
