#!/usr/bin/env ansible-playbook -i inventory.ini
---
- hosts: all
  gather_facts: true
  remote_user: pi
  become: yes
  become_user: root
  roles:
    - utils
  tags:
    - bramble
    - bootstrap

- name: setup the consul servers
  hosts: consul_servers
  become: true
  become_user: root
  gather_facts: true
  remote_user: pi
  roles:
    - { role: consul, consul_is_server: yes }
  tags:
    - consul
    - consul-servers

- name: setup the consul followers
  hosts: consul_followers
  become: true
  become_user: root
  gather_facts: true
  remote_user: pi
  roles:
    - { role: consul, consul_is_server: no }
  tags:
    - consul
