---
traefik_version: "v2.1.3"
traefik_systemd_unit_template: traefik.service.j2
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_install_dir: /usr/bin
traefik_bin_path: "{{ traefik_install_dir }}/traefik"
traefik_config_directory: /etc/traefik.d
traefik_binary_url: https://github.com/containous/traefik/releases/download/{{traefik_version}}/traefik_{{traefik_version}}_linux_armv7.tar.gz
traefik_checksum: "sha256:b1468d029279406d8686aed7d394fc75a0d69c0db6a6798b62d64663be0dc730"
traefik_config_template: traefik.toml.j2
traefik_config_file: /etc/traefik.toml
traefix_dashboard_template: dashboard.toml.j2
traefik_dashboard_file: "{{ traefik_config_directory }}/dashboard.toml"
traefik_update: no
traefix_dashboard_items:
  - name: bazarr
    host: bazarr.veverka.net
    service: bazarr@consulcatalog
    include_auth: false
  - name: couchpotato
    host: couchpotato.veverka.net
    service: couchpotato@consulcatalog
    include_auth: false
  - name: jackett
    host: jackett.veverka.net
    service: jackett@consulcatalog
    include_auth: false
  - name: minio
    host: minio.veverka.net
    service: minio@consulcatalog
    include_auth: false
  - name: minioext
    host: minioext.veverka.net
    service: minio@consulcatalog
    include_auth: false
  - name: nomad
    host: nomad.veverka.net
    service: nomad-client@consulcatalog
    include_auth: true
  - name: ombi
    host: ombi.veverka.net
    service: ombi@consulcatalog
    include_auth: false
  - name: radarr
    host: radarr.veverka.net
    service: radarr@consulcatalog
    include_auth: false
  - name: registry
    host: registry.veverka.net
    service: dockerregistry@consulcatalog
    include_auth: true
  - name: sonarr
    host: sonarr.veverka.net
    service: sonarr@consulcatalog
    include_auth: false
