---
# Required

- include: packages.yml
- include: msmtp.yml
- include: mounts.yml
- include: zsh.yml

- name: install check scripts
  template:
    src: check-service-active.j2
    dest: /usr/local/bin/check-service-active
    mode: u=rwx,g=rx,o=rx
