---
- name: install check scripts
  template:
    src: check-service-active.j2
    dest: /usr/local/bin/check-service-active
    mode: u=rwx,g=rx,o=rx
  tags:
    - utils

- name: Install packages
  apt:
    pkg:
      - curl
      - dnsutils
      - htop
      - net-tools
      - telnet
      - unzip
      - wget
  tags:
    - utils

- name: Remove existing mount for movies
  mount:
    name: /mnt/movies
    state: unmounted
  tags:
    - dockermnt
- name: Create mounted Movies directory
  file:
    path: /mnt/movies
    state: directory
  tags:
    - dockermnt
- name: Mount movies directory
  mount:
    name: /mnt/movies
    src: "//192.168.1.137/external/Movies"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
  tags:
    - dockermnt

- name: Remove existing mount for moviesSync
  mount:
    name: /mnt/movies-sync
    state: unmounted
  tags:
    - dockermnt

- name: Create mounted MoviesSync directory
  file:
    path: /mnt/movies-sync
    state: directory
  tags:
    - dockermnt

- name: Mount moviessync directory
  mount:
    name: /mnt/movies-sync
    src: "//192.168.1.137/external/Sync"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
  tags:
    - dockermnt

- name: Remove existing mount for TV
  mount:
    name: /mnt/tv
    state: unmounted
  tags:
    - dockermnt
- name: Create mounted TV directory
  file:
    path: /mnt/tv
    state: directory
  tags:
    - dockermnt

- name: Mount tv directory
  mount:
    name: /mnt/tv
    src: "//192.168.1.124/external/TV Shows"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
  tags:
    - dockermnt

- name: Remove existing mount for TVSync
  mount:
    name: /mnt/tv-sync
    state: unmounted
  tags:
    - dockermnt
- name: Create mounted TVSync directory
  file:
    path: /mnt/tv-sync
    state: directory
  tags:
    - dockermnt
- name: Mount tv directory
  mount:
    name: /mnt/tv-sync
    src: "//192.168.1.124/external/Sync"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
  tags:
    - dockermnt
- name: Create mounted config directory
  file:
    path: /mnt/configs
    state: directory
- name: Remove existing mount for configs
  mount:
    name: /mnt/configs
    state: unmounted
- name: Mount configs directory
  mount:
    name: /mnt/configs
    src: "//192.168.1.43/Public/NomadConfigs"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
