---
- name: install check scripts
  template:
    src: check-service-active.j2
    dest: /usr/local/bin/check-service-active
    mode: u=rwx,g=rx,o=rx
  tags:
    - utils

- apt:
    name: htop
    update_cache: yes
  with_items:
    - htop
    - dnsutils
    - telnet
    - curl
    - net-tools
    - unzip
    - htop
    - wget
  tags:
    - utils
