---
- name: Remove existing mounts
  mount:
    name: "{{ item.name }}"
    state: unmounted
  loop:
    - { name: "/mnt/pi-movies", src: "//192.168.1.231/external/Movies" }
    - { name: "/mnt/pi-movies-sync", src: "//192.168.1.231/external/MovieSync" }
    - { name: "/mnt/pi-tv", src: "//192.168.1.231/external/TV" }
    - { name: "/mnt/pi-tv-sync", src: "//192.168.1.231/external/TVSync" }
    - { name: "/mnt/qnap-tv", src: "//192.168.1.43/VIDEO/TV" }
    - { name: "/mnt/qnap-tv-sync", src: "//192.168.1.43/VIDEO/Sync" }
  tags:
    - dockermnt
- name: Create mounted directories
  file:
    name: "{{ item.name }}"
    state: directory
  loop:
    - { name: "/mnt/pi-movies", src: "//192.168.1.231/external/Movies" }
    - { name: "/mnt/pi-movies-sync", src: "//192.168.1.231/external/MovieSync" }
    - { name: "/mnt/pi-tv", src: "//192.168.1.231/external/TV" }
    - { name: "/mnt/pi-tv-sync", src: "//192.168.1.231/external/TVSync" }
    - { name: "/mnt/qnap-tv", src: "//192.168.1.43/VIDEO/TV" }
    - { name: "/mnt/qnap-tv-sync", src: "//192.168.1.43/VIDEO/Sync" }
  tags:
    - dockermnt
- name: Mount directories
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
  loop:
    - { name: "/mnt/pi-movies", src: "//192.168.1.231/external/Movies" }
    - { name: "/mnt/pi-movies-sync", src: "//192.168.1.231/external/MovieSync" }
    - { name: "/mnt/pi-tv", src: "//192.168.1.231/external/TV" }
    - { name: "/mnt/pi-tv-sync", src: "//192.168.1.231/external/TVSync" }
    - { name: "/mnt/qnap-tv", src: "//192.168.1.43/VIDEO/TV" }
    - { name: "/mnt/qnap-tv-sync", src: "//192.168.1.43/VIDEO/Sync" }
  tags:
    - dockermnt
