---
- name: Install msmtp and msmtp-mta
  apt:
    pkg:
      - msmtp
      - msmtp-mta
  tags:
    - msmtprc

- name: Set up /etc/msmtprc
  template:
    dest: /etc/msmtprc
    src: msmtp.conf.j2
  tags:
    - msmtprc
