###############################################################################
################################ CONFIGURE ####################################
###############################################################################

- block:
  - name: configure vault for systemd
    copy:
      src: vault.service
      dest: "{{ systemd_dir }}/vault.service"
      mode: 644
    tags:
      - vault
  - name: reload systemd
    systemd:
      daemon_reload: yes
      name: vault.service
      state: restarted
    tags:
      - vault
  - name: configure vault
    template:
      src: vault.config
      dest: /etc/vault.config
      mode: 600
    notify: restart vault
    tags:
      - vault

#  - name: register vault with consul
#    template:
#      src: vault-consul.json.j2
#      dest: /etc/consul/vault-consul.json
#      mode: 0644
#    tags:
#      - vault

  - name: enable vault
    service:
      name: vault
      enabled: yes
      state: started
    tags:
      - vault

  become: yes
  become_user: root
