# Adding in router for traefikdash
[http.routers.prtg]
  rule = "Host(`prtg.veverka.net`)"
  service = "service-prtg"

  [http.routers.prtg.tls]
    certResolver = "le" # From static configuration
    [[http.routers.prtg.tls.domains]]
      main = "prtg.veverka.net"

# Adding in router for prtg
[http.services]
  [http.services.service-prtg]
    [http.services.service-prtg.loadBalancer]
      [[http.services.service-prtg.loadBalancer.servers]]
        url = "http://192.168.1.32:8100"
