# Adding in router for traefikdash
[http.routers.winsonarrdash]
  rule = "Host(`winsonarr.veverka.net`)"
  service = "service-winsonarr"

  [http.routers.winsonarrdash.tls]
    certResolver = "le" # From static configuration
    [[http.routers.winsonarrdash.tls.domains]]
      main = "winsonarr.veverka.net"

# Adding in router for winsonarrdash
[http.services]
  [http.services.service-winsonarr]
    [http.services.service-winsonarr.loadBalancer]
      [[http.services.service-winsonarr.loadBalancer.servers]]
        url = "http://192.168.1.32:8567"
